apiVersion: apps/v1
kind: Deployment
metadata:
  name: medplum-frontend
  namespace: medplum
  labels:
    app: medplum-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medplum-frontend
  template:
    metadata:
      labels:
        app: medplum-frontend
    spec:
      # todo: wait for backend maybe?
      containers:
        - name: medplum-frontend
          imagePullPolicy: Always
          image: 554179259394.dkr.ecr.us-east-1.amazonaws.com/medplum-frontend:dev
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: medplum-frontend
  namespace: medplum
spec:
  selector:
    app: medplum-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
