name: go-svc-template - Pull Request

on: pull_request

permissions:
  pull-requests: write

jobs:
  test-and-gocyclo:
    uses: ./.github/workflows/test-and-gocyclo.yml
    secrets:
      TOKEN: ${{ secrets.CI_PAT_TOKEN_READONLY }}
    with:
      run-gocyclo: true
      post-comments: true
